"""empty message

Revision ID: a2b760579000
Revises: e33c97c84b4e
Create Date: 2017-07-14 16:25:07.070494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b760579000'
down_revision = 'e33c97c84b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('like_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'likes', ['like_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'like_id')
    # ### end Alembic commands ###
